name: Build and Release Tauri App

on:
  push:
    tags:
      - 'v*'  # 每次推送新的 tag 时触发发布流程

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Set up Node.js
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |
          npm install
          npm run tauri deps

      - name: Build Tauri app
        run: npm run tauri build

      - name: Archive Tauri build
        run: tar -czvf tauri-release.tar.gz -C src-tauri/target/release-bundle .

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: tauri-release.tar.gz
          asset_name: tauri-release.tar.gz
          asset_content_type: application/gzip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          files: tauri-release.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
